# Generated by Django 3.1.1 on 2020-10-31 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('street', models.CharField(max_length=64, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('entrance', models.CharField(max_length=10, null=True, verbose_name='Подъезд')),
                ('floor', models.CharField(max_length=3, null=True, verbose_name='Этаж')),
                ('apartment', models.CharField(max_length=10, null=True, verbose_name='Квартира')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
