# Generated by Django 3.1.1 on 2020-11-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Этаж'),
        ),
    ]
