# Generated by Django 3.1.1 on 2020-11-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20201109_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='intercom',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Домофон'),
        ),
    ]
