# Generated by Django 3.1.1 on 2020-11-09 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20201109_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator('[-,0-9][0-9]+')], verbose_name='Этаж'),
        ),
    ]
