# Generated by Django 3.1.1 on 2020-12-05 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20201111_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='CustomerUser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='CustomerUser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 22, 57, 54, 309558, tzinfo=utc)),
        ),
    ]
