# Generated by Django 3.1.4 on 2020-12-14 23:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20201206_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='CustomerUser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 23, 0, 0, 56831, tzinfo=utc)),
        ),
    ]
