# Generated by Django 3.1.4 on 2020-12-16 22:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20201215_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='CustomerUser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 22, 48, 11, 611579, tzinfo=utc)),
        ),
    ]
