# Generated by Django 3.1.4 on 2020-12-30 01:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20201230_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 1, 59, 14, 531868, tzinfo=utc)),
        ),
    ]
