# Generated by Django 3.1.4 on 2021-03-03 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_auto_20201230_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 2, 44, 1, 934102, tzinfo=utc)),
        ),
    ]
