# Generated by Django 3.1.6 on 2021-03-03 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_auto_20210303_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 2, 44, 12, 5450, tzinfo=utc)),
        ),
    ]
